# Generated by Django 2.1.7 on 2019-03-08 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Battery')),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked', models.DateTimeField(blank=True, null=True)),
                ('solved', models.DateTimeField(blank=True, null=True)),
                ('response', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representation', models.TextField()),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tryout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=255, null=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Battery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='solve',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Task'),
        ),
        migrations.AddField(
            model_name='solve',
            name='tryout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Tryout'),
        ),
        migrations.AddField(
            model_name='batterytask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Task'),
        ),
        migrations.AddField(
            model_name='battery',
            name='tasks',
            field=models.ManyToManyField(through='store.BatteryTask', to='store.Task'),
        ),
        migrations.AddField(
            model_name='battery',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Test'),
        ),
    ]
