# Generated by Django 2.1.7 on 2019-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve',
            name='correct',
        ),
        migrations.AlterField(
            model_name='solve',
            name='response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.IntegerField(max_length=255),
        ),
    ]
