# Generated by Django 2.1.7 on 2019-02-16 19:20

from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryout',
            name='completed',
            field=store.models.EpochField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tryout',
            name='started',
            field=store.models.EpochField(blank=True, null=True),
        ),
    ]
