# Generated by Django 2.1.7 on 2019-02-16 19:49

from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190216_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='picked',
            field=store.models.EpochField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='solved',
            field=store.models.EpochField(blank=True, null=True),
        ),
    ]
