# Generated by Django 2.1.7 on 2019-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190228_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tryout',
            old_name='completed',
            new_name='ended',
        ),
        migrations.AlterField(
            model_name='task',
            name='key',
            field=models.IntegerField(),
        ),
    ]
