# Generated by Django 2.1.7 on 2019-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190216_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solve',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
