# Generated by Django 2.1.7 on 2019-02-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190216_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
