# Generated by Django 2.1.7 on 2019-02-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_solve_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
