# Generated by Django 2.1.7 on 2019-02-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190219_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
