- hosts: localhost
  tasks:
  - name: "Create src.tar.gz from git ~HEAD"
    command: git archive -o src.tar.gz HEAD

- hosts: webserver
  remote_user: root

  vars:
    base_dir: /opt
    node_dist: node-v8.12.0-linux-x64

  environment:
    PATH: "{{ base_dir }}/{{ node_dist }}/bin:{{ ansible_env.PATH }}"
    NODE_ENV: "{{ base_dir}}/{{ node_dist }}/lib/node_modules"

  tasks:
  - name: "Check current version of node"
    command: node --version
    register: node_version
  
  - name: "Set fact node_version = {{ node_version.stdout }}"
    set_fact:
      node_version: "{{ node_version.stdout }}"

  - name: "Download node and npm ({{ node_dist }}) to {{ base_dir }}"
    when: node_version != "v8.12.0"
    unarchive:
      src: https://nodejs.org/dist/v8.12.0/{{ node_dist }}.tar.xz
      dest: "{{ base_dir }}"
      remote_src: yes
  
  - name: "Ensure latest pm2"
    npm:
      name: pm2
      global: yes
      state: latest

  - name: "Make directory /opt/seval"
    file:
      path: /opt/seval
      state: directory

  - name: "Extract src.tar.gz into /opt/seval"
    unarchive:
      src: src.tar.gz
      dest: /opt/seval

  - name: "Install packages.json"
    npm:
      path: /opt/seval
      state: latest
  
  - name: "Start seval"
    shell: "pm2 start --env production"
    args:
      chdir: "/opt/seval"
  
- hosts: localhost
  tasks:
  - name: "Remove src.tar.gz"
    file:
      path: src.tar.gz
      state: absent
